### ISSUE TITLE
ReanimatedError: Cannot read property 'key' of undefined, js engine: reanimated

### ISSUE THREAD

**Issue by sangramsuyog** [BooYeu/react-native-reanimated-viewer#5]
<img width="371" alt="Screen Shot 2023-04-26 at 2 07 16 PM" src="https://user-images.githubusercontent.com/90088705/234519100-2b8b9002-2172-4141-a4c7-6f5a8b413117.png">

**Comment by BooYeu** [comment]
I publish v1.0.3 to fix it. If you meet same problem after upgrade, please reopen this issue any time~

**Comment by BooYeu** [comment]
Can you provide me with the operation method to trigger this problem?

**Comment by sangramsuyog** [comment]
After reinstalling, node module, the project is working.

**Comment by BooYeu** [comment]
Does this bug appear when loading is complete, or does some other gesture interaction do it?

**Comment by sangramsuyog** [comment]
bug appear when loading is complete 

> Does this bug appear when loading is complete, or does some other gesture interaction do it?

**Comment by sangramsuyog** [comment]
> Does this bug appear when loading is complete, or does some other gesture interaction do it?


https://user-images.githubusercontent.com/90088705/235285873-a3211a57-99a9-4b2d-aa2d-8dd3f09f5499.mov

**Comment by BooYeu** [comment]
I found that the problem is caused by missing the dependency of the data parameter, you can try version 1.0.4 again.
Also, you can wrap galleryData with memo to improve performance:
`
const gallerydataWrapper = useMemo(() => gallerydata.map((el) => ({ key: `key-${el.images}`, source: { uri: el.images } })), [gallerydata]);
 <ImageViewer
    ref={imageRef}
    data={gallerydataWrapper}
  />
`

**Comment by sangramsuyog** [comment]
Thank You
